### ISSUE TITLE
mistake on function "RGB_color_Lab_difference_CIE94();"

### ISSUE THREAD

**Issue by vigneshtnj** [gi0rikas/Color-conversions#1]
In function "`RGB_color_Lab_difference_CIE94()`", line no 281, 282,

convertRGBtoXYZ(R1, G1, B1, &x1, &x1, &z1);
convertRGBtoXYZ(R2, G2, B2, &x2, &x2, &z2);

passed X values instead of Y1, Y2, 

correction:
```
convertRGBtoXYZ(R1, G1, B1, &x1, &y1, &z1);
convertRGBtoXYZ(R2, G2, B2, &x2, &y2, &z2);
```

**Comment by gegaryfa** [comment]
Good catch! Can you open a pr for this fix ?
